<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="SwatiP" failures="1" tests="1" name="Default test" time="4.156" errors="0" timestamp="2022-07-21T13:30:10 EDT">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="1.659">
    <failure type="java.lang.AssertionError" message="expected [404] but found [401]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [401]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at stepdefinitions.GetUser_UserType.status_unauthorized_access_should_be_displayed(GetUser_UserType.java:125)
at âœ½.Status 401 Unauthorized access should be displayed(file:///C:/Users/swati/git/DieticianAPI-Hackathon/src/test/resources/features/Users/GetUser_UserType.feature:37)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
